//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CGDataEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class ForumTopic
    {
        public ForumTopic()
        {
            this.ForumThreads = new HashSet<ForumThread>();
        }
    
        public System.Guid TopicId { get; set; }
        public System.Guid ForumId { get; set; }
        public string TopicTitle { get; set; }
        public string TopicDescription { get; set; }
        public bool IsPublic { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public bool IsDeleted { get; set; }
    
        public virtual Forum Forum { get; set; }
        public virtual ICollection<ForumThread> ForumThreads { get; set; }
        public virtual UserProfile UserProfile { get; set; }
    }
}
