//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CGDataEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Service_Roles
    {
        public System.Guid ServiceRoleId { get; set; }
        public System.Guid ServiceId { get; set; }
        public int RoleId { get; set; }
    
        public virtual Service Service { get; set; }
        public virtual webpages_Roles Roles { get; set; }
    }
}
