//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CGDataEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserProfile
    {
        public UserProfile()
        {
            this.webpages_Roles = new HashSet<webpages_Roles>();
            this.CreatedAnnouncements = new HashSet<Announcement>();
            this.ModifiedAnnouncements = new HashSet<Announcement>();
            this.ForumThreads = new HashSet<ForumThread>();
            this.ForumTopics = new HashSet<ForumTopic>();
            this.ForumReplies = new HashSet<ForumReply>();
        }
    
        public int UserId { get; set; }
        public string UserName { get; set; }
        public string Email { get; set; }
        public string Timezone { get; set; }
        public string PhoneNumber { get; set; }
        public string SteamHandle { get; set; }
        public bool ListInDirectory { get; set; }
        public string Signature { get; set; }
        public string AvatarFileName { get; set; }
        public Nullable<System.DateTime> BanExpireDate { get; set; }
    
        public virtual ICollection<webpages_Roles> webpages_Roles { get; set; }
        public virtual ICollection<Announcement> CreatedAnnouncements { get; set; }
        public virtual ICollection<Announcement> ModifiedAnnouncements { get; set; }
        public virtual ICollection<ForumThread> ForumThreads { get; set; }
        public virtual ICollection<ForumTopic> ForumTopics { get; set; }
        public virtual ICollection<ForumReply> ForumReplies { get; set; }
    }
}
