CREATE TABLE [dbo].[Forum]
(
	[ForumId] UNIQUEIDENTIFIER NOT NULL PRIMARY KEY DEFAULT NEWID(), 
    [ForumTitle] NCHAR(128) NOT NULL, 
    [IsPublic] BIT NOT NULL DEFAULT 0, 
    [IsDeleted] BIT NOT NULL DEFAULT 0
)
